### ISSUE TITLE
error: no such file /tmp/...

### ISSUE THREAD

**Issue by secretmango** [phantom-node/cryptreboot#7] opened 2024-10-20 20:21 UTC
I have a PC I want to setup. I used Debian because I need cryptreboot.

Default Debian install, ext4 with encrypted LVM.

```
sudo cryptreboot
Enoent: No such file or directory @ dir_chdir - /tmp/d20241020-1286-um20el/files
```

And idea?

**Comment by pepawel** [comment] 2024-10-20 20:38
Hi @secretmango, thank you for using cryptreboot :)
I've tested cryptreboot on Debian and it should work. Have you applied Debian-specific tips?
https://github.com/phantom-node/cryptreboot?tab=readme-ov-file#no-symlinks-to-the-most-recent-kernel-and-initramfs

**Comment by secretmango** [comment] 2024-10-21 10:11
I will try the tips, thank you. It is a very plain, fresh Debian 12 install.

**Comment by pepawel** [comment] 2024-10-21 14:37
I keep my fingers crossed.

**Comment by secretmango** [comment] 2024-10-23 11:43
hi, wait so am I correct that for it to work I need to have my kernel unencrypted?

Normally afaik, grub deals with the LUKS unlocking and has its own kernel? Not sure about that.

This could be an issue.

**Comment by pepawel** [comment] 2024-10-26 10:43
Cryptreboot is neutral in terms of how you store your kernel. You can keep it on an unencrypted /boot partition (the most common setup), on an encrypted partition having GRUB to unlock it, or wherever else you want. The only requirement is that the kernel and initramfs must be available to the cryptreboot when you want to reboot the system.

Were you able to restart your system using the "Troubleshooting" link I provided earlier? If not, please provide the exact commands you entered and the result you got.

**Comment by pepawel** [comment] 2024-12-14 21:35
@secretmango I'm closing the issue. If you believe the problem is still there, you can reopen it.

**Closed by pepawel** 2024-12-14 21:35 UTC
